### ISSUE TITLE
Usage of fetch browser api in server side

### ISSUE THREAD

**Issue by ThomasKientz** [bdrtsky/nuxt-dev-to-clone#6]
https://github.com/bdrtsky/nuxt-dev-to-clone/blob/a59de99bfaf5ae7210e4cb7e650ee19870d4cd06/pages/index.vue#L58

Fetch (not the nuxt hook) is a browser API, how is it possible that you use it in server side (in the `fetch` hook)?

**Comment by Atinux** [comment]
@ThomasKientz Nuxt is already adding a polyfill for Node using `node-fetch`

**Comment by ThomasKientz** [comment]
@Atinux Dark magic ! This should be documented IMO :)

**Comment by Atinux** [comment]
You are more than right
