### ISSUE TITLE
Copyright Violation & Takedown Notice (dev.to)

### ISSUE THREAD

**Issue by michael-tharrington** [bdrtsky/nuxt-dev-to-clone#9]
Hello,

It has come to our attention that articles published through this app/site - https://dev-clone.nuxtjs.app/ have improperly taken content from DEV (dev.to). This violates our author’s rights, their copyright protections, and the Terms of Use of our platform (https://dev.to/terms).

We demand in the strongest possible terms that you cease and desist, and that you immediately take down this site. 

This is a formal notice that you must immediately cease and desist from taking content from dev.to in this manner going forward.

We expect a speedy and satisfactory response.

Michael (Senior Community Manager at DEV/Forem)

**Comment by Atinux** [comment]
It has been removed, sorry about this @michael-tharrington

**Comment by michael-tharrington** [comment]
Thanks very much! It's okay.
